2024-04-12 18:59:45,555 - error_logs - ERROR - (psycopg2.errors.UndefinedColumn) column "value" of relation "like" does not exist
LINE 1: ... INTO public."like" (timestamp, blog_id, user_id, value) VAL...
                                                             ^

[SQL: INSERT INTO public."like" (timestamp, blog_id, user_id, value) VALUES (%(timestamp)s, %(blog_id)s, %(user_id)s, %(value)s) RETURNING public."like".id]
[parameters: {'timestamp': datetime.datetime(2024, 4, 12, 18, 59, 42, 402245), 'blog_id': 1, 'user_id': 4, 'value': None}]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column "value" of relation "like" does not exist
LINE 1: ... INTO public."like" (timestamp, blog_id, user_id, value) VAL...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\model\request_model.py", line 43, in get_likes
    like_session.commit()
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4296, in flush
    self._flush(objects)
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4431, in _flush
    with util.safe_reraise():
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4392, in _flush
    flush_context.execute()
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1421, in execute
    return meth(
           ^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1643, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1849, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1989, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2356, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "value" of relation "like" does not exist
LINE 1: ... INTO public."like" (timestamp, blog_id, user_id, value) VAL...
                                                             ^

[SQL: INSERT INTO public."like" (timestamp, blog_id, user_id, value) VALUES (%(timestamp)s, %(blog_id)s, %(user_id)s, %(value)s) RETURNING public."like".id]
[parameters: {'timestamp': datetime.datetime(2024, 4, 12, 18, 59, 42, 402245), 'blog_id': 1, 'user_id': 4, 'value': None}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-04-12 18:59:45,566 - error_logs - ERROR - (psycopg2.errors.UndefinedColumn) column "value" of relation "like" does not exist
LINE 1: ... INTO public."like" (timestamp, blog_id, user_id, value) VAL...
                                                             ^

[SQL: INSERT INTO public."like" (timestamp, blog_id, user_id, value) VALUES (%(timestamp)s, %(blog_id)s, %(user_id)s, %(value)s) RETURNING public."like".id]
[parameters: {'timestamp': datetime.datetime(2024, 4, 12, 18, 59, 42, 402245), 'blog_id': 1, 'user_id': 4, 'value': None}]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column "value" of relation "like" does not exist
LINE 1: ... INTO public."like" (timestamp, blog_id, user_id, value) VAL...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\controller\request_controller.py", line 29, in get_likes
    data.get_likes(blog_id, user_id)
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\model\request_model.py", line 43, in get_likes
    like_session.commit()
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4296, in flush
    self._flush(objects)
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4431, in _flush
    with util.safe_reraise():
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4392, in _flush
    flush_context.execute()
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1421, in execute
    return meth(
           ^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1643, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1849, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1989, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2356, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "value" of relation "like" does not exist
LINE 1: ... INTO public."like" (timestamp, blog_id, user_id, value) VAL...
                                                             ^

[SQL: INSERT INTO public."like" (timestamp, blog_id, user_id, value) VALUES (%(timestamp)s, %(blog_id)s, %(user_id)s, %(value)s) RETURNING public."like".id]
[parameters: {'timestamp': datetime.datetime(2024, 4, 12, 18, 59, 42, 402245), 'blog_id': 1, 'user_id': 4, 'value': None}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-04-12 19:06:13,008 - error_logs - ERROR - (psycopg2.errors.UndefinedColumn) column "value" of relation "like" does not exist
LINE 1: ... INTO public."like" (timestamp, blog_id, user_id, value) VAL...
                                                             ^

[SQL: INSERT INTO public."like" (timestamp, blog_id, user_id, value) VALUES (%(timestamp)s, %(blog_id)s, %(user_id)s, %(value)s) RETURNING public."like".id]
[parameters: {'timestamp': datetime.datetime(2024, 4, 12, 19, 6, 8, 695595), 'blog_id': 1, 'user_id': 4, 'value': None}]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column "value" of relation "like" does not exist
LINE 1: ... INTO public."like" (timestamp, blog_id, user_id, value) VAL...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\model\request_model.py", line 43, in get_likes
    like_session.commit()
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4296, in flush
    self._flush(objects)
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4431, in _flush
    with util.safe_reraise():
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4392, in _flush
    flush_context.execute()
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1421, in execute
    return meth(
           ^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1643, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1849, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1989, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2356, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "value" of relation "like" does not exist
LINE 1: ... INTO public."like" (timestamp, blog_id, user_id, value) VAL...
                                                             ^

[SQL: INSERT INTO public."like" (timestamp, blog_id, user_id, value) VALUES (%(timestamp)s, %(blog_id)s, %(user_id)s, %(value)s) RETURNING public."like".id]
[parameters: {'timestamp': datetime.datetime(2024, 4, 12, 19, 6, 8, 695595), 'blog_id': 1, 'user_id': 4, 'value': None}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-04-12 19:06:13,015 - error_logs - ERROR - (psycopg2.errors.UndefinedColumn) column "value" of relation "like" does not exist
LINE 1: ... INTO public."like" (timestamp, blog_id, user_id, value) VAL...
                                                             ^

[SQL: INSERT INTO public."like" (timestamp, blog_id, user_id, value) VALUES (%(timestamp)s, %(blog_id)s, %(user_id)s, %(value)s) RETURNING public."like".id]
[parameters: {'timestamp': datetime.datetime(2024, 4, 12, 19, 6, 8, 695595), 'blog_id': 1, 'user_id': 4, 'value': None}]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column "value" of relation "like" does not exist
LINE 1: ... INTO public."like" (timestamp, blog_id, user_id, value) VAL...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\controller\request_controller.py", line 29, in get_likes
    data.get_likes(blog_id, user_id)
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\model\request_model.py", line 43, in get_likes
    like_session.commit()
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4296, in flush
    self._flush(objects)
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4431, in _flush
    with util.safe_reraise():
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4392, in _flush
    flush_context.execute()
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1421, in execute
    return meth(
           ^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1643, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1849, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1989, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2356, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "value" of relation "like" does not exist
LINE 1: ... INTO public."like" (timestamp, blog_id, user_id, value) VAL...
                                                             ^

[SQL: INSERT INTO public."like" (timestamp, blog_id, user_id, value) VALUES (%(timestamp)s, %(blog_id)s, %(user_id)s, %(value)s) RETURNING public."like".id]
[parameters: {'timestamp': datetime.datetime(2024, 4, 12, 19, 6, 8, 695595), 'blog_id': 1, 'user_id': 4, 'value': None}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-04-12 19:11:12,313 - error_logs - ERROR - type object 'Like' has no attribute 'value'
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\model\request_model.py", line 34, in get_likes
    data_updated = like_session.query(Like.value).filter(Like.user_id == user_id, Like.blog_id == blog_id)
                                      ^^^^^^^^^^
AttributeError: type object 'Like' has no attribute 'value'
2024-04-12 19:11:12,314 - error_logs - ERROR - type object 'Like' has no attribute 'value'
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\controller\request_controller.py", line 29, in get_likes
    data.get_likes(likes_dislikes, blog_id, user_id)
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\model\request_model.py", line 34, in get_likes
    data_updated = like_session.query(Like.value).filter(Like.user_id == user_id, Like.blog_id == blog_id)
                                      ^^^^^^^^^^
AttributeError: type object 'Like' has no attribute 'value'
2024-04-12 19:29:16,011 - error_logs - ERROR - 
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\model\request_model.py", line 62, in get_likes
    elif like_data == 'false':
         ^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
                      ^^^^^^^^^^^^^
bdb.BdbQuit
2024-04-12 19:29:16,119 - error_logs - ERROR - 
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\controller\request_controller.py", line 29, in get_likes
    data.get_likes(likes_dislikes, blog_id, user_id)
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\model\request_model.py", line 62, in get_likes
    elif like_data == 'false':
         ^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
                      ^^^^^^^^^^^^^
bdb.BdbQuit
2024-04-12 20:54:53,002 - error_logs - ERROR - 'RequestOperations' object has no attribute 'get_all_likes_for_uses'
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\controller\request_controller.py", line 142, in get_all_user_likes
    all_like_data = data.get_all_likes_for_uses()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RequestOperations' object has no attribute 'get_all_likes_for_uses'. Did you mean: 'get_all_likes_for_users'?
2024-04-12 20:58:19,959 - error_logs - ERROR - 'RequestOperations' object has no attribute 'get_all_dislikes_for_uers'
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\controller\request_controller.py", line 161, in get_all_user_dislikes
    all_like_data = data.get_all_dislikes_for_uers()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RequestOperations' object has no attribute 'get_all_dislikes_for_uers'. Did you mean: 'get_all_dislikes_for_users'?
2024-04-12 22:23:45,331 - error_logs - ERROR - 
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\model\request_model.py", line 62, in get_likes
    api_url = "http://35.171.3.193:8001/api/send-blog-notification/"
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
                      ^^^^^^^^^^^^^
bdb.BdbQuit
2024-04-12 22:23:45,424 - error_logs - ERROR - 
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\controller\request_controller.py", line 29, in get_likes
    data.get_likes(likes_dislikes, blog_id, user_id)
  File "C:\Users\HP\Desktop\Projects\webtech\Coursework\Likes-Comments\model\request_model.py", line 62, in get_likes
    api_url = "http://35.171.3.193:8001/api/send-blog-notification/"
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
                      ^^^^^^^^^^^^^
bdb.BdbQuit
